/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSyncRouteImport } from './routes/_authenticated/sync'
import { Route as AuthenticatedProjekteRouteImport } from './routes/_authenticated/projekte'
import { Route as AuthenticatedProjekteNeuRouteImport } from './routes/_authenticated/projekte.neu'
import { Route as AuthenticatedProjektIdRouteImport } from './routes/_authenticated/projekt.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSyncRoute = AuthenticatedSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjekteRoute = AuthenticatedProjekteRouteImport.update({
  id: '/projekte',
  path: '/projekte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjekteNeuRoute =
  AuthenticatedProjekteNeuRouteImport.update({
    id: '/neu',
    path: '/neu',
    getParentRoute: () => AuthenticatedProjekteRoute,
  } as any)
const AuthenticatedProjektIdRoute = AuthenticatedProjektIdRouteImport.update({
  id: '/projekt/$id',
  path: '/projekt/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/projekte': typeof AuthenticatedProjekteRouteWithChildren
  '/sync': typeof AuthenticatedSyncRoute
  '/projekt/$id': typeof AuthenticatedProjektIdRoute
  '/projekte/neu': typeof AuthenticatedProjekteNeuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/projekte': typeof AuthenticatedProjekteRouteWithChildren
  '/sync': typeof AuthenticatedSyncRoute
  '/projekt/$id': typeof AuthenticatedProjektIdRoute
  '/projekte/neu': typeof AuthenticatedProjekteNeuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/projekte': typeof AuthenticatedProjekteRouteWithChildren
  '/_authenticated/sync': typeof AuthenticatedSyncRoute
  '/_authenticated/projekt/$id': typeof AuthenticatedProjektIdRoute
  '/_authenticated/projekte/neu': typeof AuthenticatedProjekteNeuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/projekte'
    | '/sync'
    | '/projekt/$id'
    | '/projekte/neu'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/projekte' | '/sync' | '/projekt/$id' | '/projekte/neu'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/projekte'
    | '/_authenticated/sync'
    | '/_authenticated/projekt/$id'
    | '/_authenticated/projekte/neu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sync': {
      id: '/_authenticated/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof AuthenticatedSyncRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projekte': {
      id: '/_authenticated/projekte'
      path: '/projekte'
      fullPath: '/projekte'
      preLoaderRoute: typeof AuthenticatedProjekteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projekte/neu': {
      id: '/_authenticated/projekte/neu'
      path: '/neu'
      fullPath: '/projekte/neu'
      preLoaderRoute: typeof AuthenticatedProjekteNeuRouteImport
      parentRoute: typeof AuthenticatedProjekteRoute
    }
    '/_authenticated/projekt/$id': {
      id: '/_authenticated/projekt/$id'
      path: '/projekt/$id'
      fullPath: '/projekt/$id'
      preLoaderRoute: typeof AuthenticatedProjektIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedProjekteRouteChildren {
  AuthenticatedProjekteNeuRoute: typeof AuthenticatedProjekteNeuRoute
}

const AuthenticatedProjekteRouteChildren: AuthenticatedProjekteRouteChildren = {
  AuthenticatedProjekteNeuRoute: AuthenticatedProjekteNeuRoute,
}

const AuthenticatedProjekteRouteWithChildren =
  AuthenticatedProjekteRoute._addFileChildren(
    AuthenticatedProjekteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProjekteRoute: typeof AuthenticatedProjekteRouteWithChildren
  AuthenticatedSyncRoute: typeof AuthenticatedSyncRoute
  AuthenticatedProjektIdRoute: typeof AuthenticatedProjektIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProjekteRoute: AuthenticatedProjekteRouteWithChildren,
  AuthenticatedSyncRoute: AuthenticatedSyncRoute,
  AuthenticatedProjektIdRoute: AuthenticatedProjektIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
