/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedEinstellungenRouteImport } from './routes/_authenticated/einstellungen'
import { Route as AuthenticatedProjekteIndexRouteImport } from './routes/_authenticated/projekte.index'
import { Route as AuthenticatedProjekteNeuRouteImport } from './routes/_authenticated/projekte.neu'
import { Route as AuthenticatedProjektIdIndexRouteImport } from './routes/_authenticated/projekt.$id.index'
import { Route as AuthenticatedProjektIdVorschauRouteImport } from './routes/_authenticated/projekt.$id.vorschau'
import { Route as AuthenticatedProjektIdRaumNeuRouteImport } from './routes/_authenticated/projekt.$id.raum.neu'
import { Route as AuthenticatedProjektIdRaumRaumIdRouteImport } from './routes/_authenticated/projekt.$id.raum.$raumId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEinstellungenRoute =
  AuthenticatedEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjekteIndexRoute =
  AuthenticatedProjekteIndexRouteImport.update({
    id: '/projekte/',
    path: '/projekte/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjekteNeuRoute =
  AuthenticatedProjekteNeuRouteImport.update({
    id: '/projekte/neu',
    path: '/projekte/neu',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjektIdIndexRoute =
  AuthenticatedProjektIdIndexRouteImport.update({
    id: '/projekt/$id/',
    path: '/projekt/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjektIdVorschauRoute =
  AuthenticatedProjektIdVorschauRouteImport.update({
    id: '/projekt/$id/vorschau',
    path: '/projekt/$id/vorschau',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjektIdRaumNeuRoute =
  AuthenticatedProjektIdRaumNeuRouteImport.update({
    id: '/projekt/$id/raum/neu',
    path: '/projekt/$id/raum/neu',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjektIdRaumRaumIdRoute =
  AuthenticatedProjektIdRaumRaumIdRouteImport.update({
    id: '/projekt/$id/raum/$raumId',
    path: '/projekt/$id/raum/$raumId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/projekte/neu': typeof AuthenticatedProjekteNeuRoute
  '/projekte/': typeof AuthenticatedProjekteIndexRoute
  '/projekt/$id/vorschau': typeof AuthenticatedProjektIdVorschauRoute
  '/projekt/$id/': typeof AuthenticatedProjektIdIndexRoute
  '/projekt/$id/raum/$raumId': typeof AuthenticatedProjektIdRaumRaumIdRoute
  '/projekt/$id/raum/neu': typeof AuthenticatedProjektIdRaumNeuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/projekte/neu': typeof AuthenticatedProjekteNeuRoute
  '/projekte': typeof AuthenticatedProjekteIndexRoute
  '/projekt/$id/vorschau': typeof AuthenticatedProjektIdVorschauRoute
  '/projekt/$id': typeof AuthenticatedProjektIdIndexRoute
  '/projekt/$id/raum/$raumId': typeof AuthenticatedProjektIdRaumRaumIdRoute
  '/projekt/$id/raum/neu': typeof AuthenticatedProjektIdRaumNeuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/_authenticated/projekte/neu': typeof AuthenticatedProjekteNeuRoute
  '/_authenticated/projekte/': typeof AuthenticatedProjekteIndexRoute
  '/_authenticated/projekt/$id/vorschau': typeof AuthenticatedProjektIdVorschauRoute
  '/_authenticated/projekt/$id/': typeof AuthenticatedProjektIdIndexRoute
  '/_authenticated/projekt/$id/raum/$raumId': typeof AuthenticatedProjektIdRaumRaumIdRoute
  '/_authenticated/projekt/$id/raum/neu': typeof AuthenticatedProjektIdRaumNeuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/einstellungen'
    | '/projekte/neu'
    | '/projekte/'
    | '/projekt/$id/vorschau'
    | '/projekt/$id/'
    | '/projekt/$id/raum/$raumId'
    | '/projekt/$id/raum/neu'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/einstellungen'
    | '/projekte/neu'
    | '/projekte'
    | '/projekt/$id/vorschau'
    | '/projekt/$id'
    | '/projekt/$id/raum/$raumId'
    | '/projekt/$id/raum/neu'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/einstellungen'
    | '/_authenticated/projekte/neu'
    | '/_authenticated/projekte/'
    | '/_authenticated/projekt/$id/vorschau'
    | '/_authenticated/projekt/$id/'
    | '/_authenticated/projekt/$id/raum/$raumId'
    | '/_authenticated/projekt/$id/raum/neu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/einstellungen': {
      id: '/_authenticated/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof AuthenticatedEinstellungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projekte/': {
      id: '/_authenticated/projekte/'
      path: '/projekte'
      fullPath: '/projekte/'
      preLoaderRoute: typeof AuthenticatedProjekteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projekte/neu': {
      id: '/_authenticated/projekte/neu'
      path: '/projekte/neu'
      fullPath: '/projekte/neu'
      preLoaderRoute: typeof AuthenticatedProjekteNeuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projekt/$id/': {
      id: '/_authenticated/projekt/$id/'
      path: '/projekt/$id'
      fullPath: '/projekt/$id/'
      preLoaderRoute: typeof AuthenticatedProjektIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projekt/$id/vorschau': {
      id: '/_authenticated/projekt/$id/vorschau'
      path: '/projekt/$id/vorschau'
      fullPath: '/projekt/$id/vorschau'
      preLoaderRoute: typeof AuthenticatedProjektIdVorschauRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projekt/$id/raum/neu': {
      id: '/_authenticated/projekt/$id/raum/neu'
      path: '/projekt/$id/raum/neu'
      fullPath: '/projekt/$id/raum/neu'
      preLoaderRoute: typeof AuthenticatedProjektIdRaumNeuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projekt/$id/raum/$raumId': {
      id: '/_authenticated/projekt/$id/raum/$raumId'
      path: '/projekt/$id/raum/$raumId'
      fullPath: '/projekt/$id/raum/$raumId'
      preLoaderRoute: typeof AuthenticatedProjektIdRaumRaumIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEinstellungenRoute: typeof AuthenticatedEinstellungenRoute
  AuthenticatedProjekteNeuRoute: typeof AuthenticatedProjekteNeuRoute
  AuthenticatedProjekteIndexRoute: typeof AuthenticatedProjekteIndexRoute
  AuthenticatedProjektIdVorschauRoute: typeof AuthenticatedProjektIdVorschauRoute
  AuthenticatedProjektIdIndexRoute: typeof AuthenticatedProjektIdIndexRoute
  AuthenticatedProjektIdRaumRaumIdRoute: typeof AuthenticatedProjektIdRaumRaumIdRoute
  AuthenticatedProjektIdRaumNeuRoute: typeof AuthenticatedProjektIdRaumNeuRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEinstellungenRoute: AuthenticatedEinstellungenRoute,
  AuthenticatedProjekteNeuRoute: AuthenticatedProjekteNeuRoute,
  AuthenticatedProjekteIndexRoute: AuthenticatedProjekteIndexRoute,
  AuthenticatedProjektIdVorschauRoute: AuthenticatedProjektIdVorschauRoute,
  AuthenticatedProjektIdIndexRoute: AuthenticatedProjektIdIndexRoute,
  AuthenticatedProjektIdRaumRaumIdRoute: AuthenticatedProjektIdRaumRaumIdRoute,
  AuthenticatedProjektIdRaumNeuRoute: AuthenticatedProjektIdRaumNeuRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
